// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ytgFK-PX977zBR-kQ40YXqFtKISgfqI',
    appId: '1:840876183094:android:8fb5a5f28c33cd9a78d297',
    messagingSenderId: '840876183094',
    projectId: 'game-terong',
    storageBucket: 'game-terong.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdQfXOd0SQlWyZMJOZlUyInQhgGo7cDN0',
    appId: '1:840876183094:web:cd98ff64887f0e5778d297',
    messagingSenderId: '840876183094',
    projectId: 'game-terong',
    authDomain: 'game-terong.firebaseapp.com',
    storageBucket: 'game-terong.appspot.com',
    measurementId: 'G-P50ZZYEP7Q',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdQfXOd0SQlWyZMJOZlUyInQhgGo7cDN0',
    appId: '1:840876183094:web:cd98ff64887f0e5778d297',
    messagingSenderId: '840876183094',
    projectId: 'game-terong',
    authDomain: 'game-terong.firebaseapp.com',
    storageBucket: 'game-terong.appspot.com',
    measurementId: 'G-P50ZZYEP7Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSitrXihN9qiMmfT7ukpXUhZJRZK4c8EQ',
    appId: '1:840876183094:ios:bb9f9914037b242578d297',
    messagingSenderId: '840876183094',
    projectId: 'game-terong',
    storageBucket: 'game-terong.appspot.com',
    androidClientId: '840876183094-uhcpg1putn26ga0q5p0uobkm04iq8o76.apps.googleusercontent.com',
    iosClientId: '840876183094-7s3g7igsahfh863vel9lft1snijjo2bh.apps.googleusercontent.com',
    iosBundleId: 'com.akugt.gameterong',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSitrXihN9qiMmfT7ukpXUhZJRZK4c8EQ',
    appId: '1:840876183094:ios:bb9f9914037b242578d297',
    messagingSenderId: '840876183094',
    projectId: 'game-terong',
    storageBucket: 'game-terong.appspot.com',
    androidClientId: '840876183094-uhcpg1putn26ga0q5p0uobkm04iq8o76.apps.googleusercontent.com',
    iosClientId: '840876183094-7s3g7igsahfh863vel9lft1snijjo2bh.apps.googleusercontent.com',
    iosBundleId: 'com.akugt.gameterong',
  );

}